// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int higher_05 = 0;
		int lowerOrEqual_05 = 0;
		for(int i = 0; i < Integer.parseInt(args[0]); i++)
		{
			if (Math.random() > 0.5){

				higher_05++;
			}
			else lowerOrEqual_05++;
		}
		System.out.println("> 0.5: " + higher_05 + " times");
		System.out.println("<= 0.5: " + lowerOrEqual_05 + " times");
		if (lowerOrEqual_05 > higher_05 && higher_05 != 0 && lowerOrEqual_05 != 0)
		{
			System.out.println("ratio: " + (double) higher_05/lowerOrEqual_05);
		}
		else if (lowerOrEqual_05 < higher_05 && higher_05 != 0 && lowerOrEqual_05 != 0)
		{
			System.out.println("ratio: " + (double) lowerOrEqual_05/higher_05);

		}
		else if(higher_05 != 0 && lowerOrEqual_05 != 0) System.out.println("1");
							}
}
